### ISSUE TITLE
SMBIOS change problem

### ISSUE THREAD

**Issue by CAR1R1** [tctien342/Dell-Inspiron-7591-Hackintosh#20]
My device is inspiron 7590 (the difference with 7591 is outside look)
when i generate SMBIOS in OpencoreConfigurator and reboot
screen just stay at the dell logo and showed

> OCS: No schema for ProtectSecureBoot at 9 index
> OCS: No schema for DummyPowerManagement at 6 index
>.....

i also changed Misc-Security-Vault into Optional  but it don't work

by the way, in macOS, my touchpad don't work and i need to press L-Alt instead Win key as Command 

Forgive my awful English;)

**Comment by Pinming** [comment]
1) If you are using Opencore `0.5.6`, I advice you to modify your `config.plist` according to this post strictly: https://shuiyunxc.gitee.io/2020/02/17/difference/index/. Not only `Misc-Security-Vault`, there are many items need to modify. You can try older version of Opencore (such as `0.5.5`) to avoid this operation.
2) About the touchpad, please make sure that your kexts and SSDTs are same as this repo.
3) `L-Alt = Command` is because the keyboard on laptop is PS2, it is normal.

**Comment by CAR1R1** [comment]
我使用的就是这个repo的驱动

Im using the kexts and SSDTs provided by this repo

**Comment by tctien342** [comment]
> 我使用的就是这个repo的驱动
> 
> Im using the kexts and SSDTs provided by this repo

Need to rebuild kext after install or update by using Kextutility
If you use OpencoreConfigurator pls dont update it to lastest ver bcs it will update the config to match lastest version of opencore in github/master, not release so will cause conflict! => Use Xcode or PlistEditPro instead
