### ISSUE TITLE
build command error

### ISSUE THREAD

**Issue by Slothtron** [tctien342/Dell-Inspiron-7591-Hackintosh#60]
I run the command `python3 update.py --build`, but get some errors.

![image](https://user-images.githubusercontent.com/66720509/92669426-1098da80-f344-11ea-9e7e-2896c5738c0f.png)

**Comment by tctien342** [comment]
lol, sorry for this, forgot to change branch, i will fix this and upstream to 0.6.1 today!

**Comment by Slothtron** [comment]
@tctien342 so, could you build a new oc zip for release? thank you

**Comment by Slothtron** [comment]
@tctien342 hello, I try to update from new repo, but there have some errors yet.
I try to add some headers to request method, it have a great work.
![image](https://user-images.githubusercontent.com/66720509/92838187-10b2dc00-f411-11ea-8d4f-82a12f28f5fe.png)
![image](https://user-images.githubusercontent.com/66720509/92838245-20cabb80-f411-11ea-84d2-827a2214650a.png)

**Comment by Slothtron** [comment]
@tctien342 but the old error
![image](https://user-images.githubusercontent.com/66720509/92838941-f75e5f80-f411-11ea-8d77-3b21c2d5889b.png)

**Comment by tctien342** [comment]
The `403 rate limit` happen when u try to build many time and github reject it bcs call too many API, the `base 10` error should be fixed in lastest commit as i build success, you can try this:
+ Still trying to fix HDMI audio and i will release it
[INSPIRON-759x-OC-200910.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/5205638/INSPIRON-759x-OC-200910.zip)

**Comment by Slothtron** [comment]
ok，thanks
